[package]
name = "stignore-agent"
version = "0.1.0"
edition = "2021"
authors = ["Michael Robbins"]

[dependencies]
axum = "0.6.20"
serde = { version="1.0.192", features=["derive"] }
tokio = { version="1.34.0", features=["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
toml = "0.8.8"