[agent]
port = 3000
name = "Agent Smith"
base_path = "C:\\media"
api_key = "550e8400-e29b-41d4-a716-446655440000"

[[categories]]
id = "movies"
name = "Movies"
relative_path = "movies\\"

[[categories]]
id = "tv"
name = "TV Shows"
relative_path = "tv\\"
