[agent]
port = 3000
name = "Agent Smith"
base_path = "C:\\media"

[[categories]]
id = "movies"
name = "Movies"
relative_path = "movies\\"

[[categories]]
id = "tv"
name = "TV Shows"
relative_path = "tv\\"